.TH CALCULATORE 1 "August 2024" "1.0.0" "Calculatore Manual"
.SH NAME
calculatore \- A simple command-line calculator
.SH SYNOPSIS
.B calculatore
[options] [expression]
.SH DESCRIPTION
\fBcalculatore\fR is a simple command-line calculator that allows you to perform basic arithmetic operations.
You can enter calculations using numbers and operators, or numbers with operators written as words.
.SH OPTIONS
.TP
.B \-\-help
Show help information.
.TP
.B \-\-version
Show the version of calculatore.
.SH OPERATOR SYNTAX
Calculations can be performed using:
.TP
.B +
Addition
.TP
.B \-
Subtraction
.TP
.B \*
Multiplication
.TP
.B /
Division
.TP
Or using words:
.TP
.B "plus"
Addition
.TP
.B "minus"
Subtraction
.TP
.B "times"
Multiplication
.TP
.B "divided by"
Division
.SH EXAMPLES
.TP
.B calculatore 5 + 3
Calculates the result of 5 plus 3.
.TP
.B calculatore 10 divided by 2
Calculates the result of 10 divided by 2.
.TP
.B calculatore 8 times 7
Calculates the result of 8 times 7.
.TP
.B calculatore 14 minus 4
Calculates the result of 14 minus 4.
.SH EXITING
To exit the calculator, press CTRL-C. To reset the calculator, type in "reset" and press Enter.
.SH AUTHOR
Your Name <doribenbass@gmail.com>
